eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka/
#服务配置
server:
  port: 9002
#spring配置
spring:
  #1.应用配置
  application:
    name: ihrm-system #指定服务名
  #2.数据库连接池
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ihrm?useUnicode=true&characterEncoding=utf8
    username: root
    password: a13413350960
  #3.JPA
  jpa:
    database: MySQL
    show-sql: true
    open-in-view: true
  redis:
    host: 127.0.0.1
    port: 6379

jwt:
  config:
      key: saas-ihrm
      ttl: 3600000
ai:
  appId: 21285980
  apiKey: rSgBQnH1LB982dGGTijdU9dS
  secretKey: ONtds9157yCti7hosobiwj2Qzgv939HD
  imageType: BASE64
  groupId: itcast
qr:
  url: https://localhost:8080/#/facelogin